### ISSUE TITLE
rp-tool generated healtcheck failed in mesosphere, had to revert to curl one

### ISSUE THREAD

**Issue by ktoso** [lightbend/reactive-lib#69] opened 2018-07-12 12:00 UTC
I'll try to figure out what version of mesos this was.. but it seemed to fail with the http requests being invalid -- not including the host header AFAIR...

Would love to have more detailed info but don't have access to the env currently.

**Comment by alanngai** [comment] 2018-07-12 17:37
closing as duplicate of lightbend/reactive-cli#162

**Closed by alanngai** 2018-07-12 17:37 UTC

**Comment by ktoso** [comment] 2018-07-13 03:38
Ah wrong repo, thanks Alan
